server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: amigoscode
    password: password
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
